/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mms.struts.action;

import java.lang.reflect.InvocationTargetException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.mms.dao.IAssetType;
import com.mms.pojo.AssetType;
import com.mms.serviceImp.AssetTypeServiceImp;
import com.mms.struts.form.StockForm;
import com.mms.struts.form.AssetTypeForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/assetType" name="assetTypeForm" parameter="method" scope="request" validate="true"
 */
public class AssetTypeAction extends DispatchAction {
	private AssetTypeServiceImp ats;
	public AssetTypeServiceImp getAts() {
		return ats;
	}
	public void setAts(AssetTypeServiceImp ats) {
		this.ats = ats;
	}
	
	private IAssetType at;

	public IAssetType getAt() {
		return at;
	}

	public void setAt(IAssetType at) {
		this.at = at;
	}
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AssetTypeForm assetTypeForm = (AssetTypeForm) form;
		AssetType atp=new AssetType();
		try {
			BeanUtils.copyProperties(atp, assetTypeForm);
		} catch (IllegalAccessException e) {			
			e.printStackTrace();
		} catch (InvocationTargetException e) {			
			e.printStackTrace();
		}
		ats.addType(atp);
		return mapping.findForward("add");
	}
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		request.setAttribute("kl", at.findAll());
		return mapping.findForward("list");
	}
	//列出所有资产类型
	public ActionForward listassetType(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		request.setAttribute("kl", at.findAll());
		return mapping.findForward("depreciation_Chart");
	}
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		AssetType atype=new AssetType();
		String id=request.getParameter("d");
		Integer id1=Integer.parseInt(id);
		atype=at.findById(id1);
		at.delete(atype);
		return mapping.findForward("add");
	}
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AssetType atype=new AssetType();
		String id=request.getParameter("d");
		Integer id1=Integer.parseInt(id);
		atype=at.findById(id1);		
		request.setAttribute("edit", atype);
		return mapping.findForward("edit");
	}
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AssetTypeForm assetTypeForm = (AssetTypeForm) form;
		AssetType atp=new AssetType();
		try {
			BeanUtils.copyProperties(atp, assetTypeForm);
			System.out.print(atp.getAssetTypeId());
		} catch (IllegalAccessException e) {			
			e.printStackTrace();
		} catch (InvocationTargetException e) {			
			e.printStackTrace();
		}
		ats.updateType(atp);
		return mapping.findForward("add");
	}
	//ת��addKindForm.jsp
	public ActionForward addKindForm(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		return mapping.findForward("addKindForm");
	}
}