/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mms.struts.action;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.management.relation.Role;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.mms.dao.IDesign;
import com.mms.dao.IStock;
import com.mms.pojo.Degisn;
import com.mms.pojo.Stock;
import com.mms.pojo.TUser;
import com.mms.struts.form.StockForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2009
 * 
 * XDoclet definition:
 * @struts.action path="/asset" name="assetForm" scope="request" validate="true"
 * @struts.action-forward name="add" path="/infoManage/addKindForm.jsp"
 */
public class StockAction extends DispatchAction {
	
	private IStock is;
	public IStock getIs() {
		return is;
	}
	public void setIs(IStock is) {
		this.is = is;
	}
	private IDesign ide;
	
	public IDesign getIde() {
		return ide;
	}
	public void setIde(IDesign ide) {
		this.ide = ide;
	}
	//列出所有股票
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List l = new ArrayList();
		List stock= new ArrayList();
        l = is.findAll();
        for(int i=0;i<l.size();i++)
        {
        	Stock s = new Stock();
        	s = (Stock) l.get(i);
        	System.out.println("<<<<<"+s.getStockCode()+" "+s.getStockInfo());
        	stock.add(s);
        }
        request.setAttribute("stock", stock);
		return mapping.findForward("listall");
	}
	//列出所有股票
	public ActionForward liststock(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List l = new ArrayList();
		List stock= new ArrayList();
        l = is.findAll();
        for(int i=0;i<l.size();i++)
        {
        	Stock s = new Stock();
        	s = (Stock) l.get(i);
        	stock.add(s);
        }
        request.setAttribute("stock", stock);
		return mapping.findForward("list");
	}
	//添加股票信息
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockForm stock = (StockForm) form;
		Stock sto = new Stock();
		sto.setStockCode(stock.getStockCode());
		sto.setStockInfo(stock.getStockInfo());
		sto.setStockName(stock.getStockName());
		is.save(sto);
		return mapping.findForward("addstock");
	}
	//列出用户没有选过的股票
	public ActionForward listbyuser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List l = new ArrayList();
		List stock= new ArrayList();
		TUser user = new TUser();
		user = (TUser)request.getSession().getAttribute("user");
        l = is.listbyuser(user.getUserId().toString());
        for(int i=0;i<l.size();i++)
        {
        	Stock s = new Stock();
        	s = (Stock) l.get(i);
        	stock.add(s);
        }
        request.setAttribute("stock", stock);
		return mapping.findForward("listbyuser");
	}
	//自选股添加
	public ActionForward addstock(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id = request.getParameter("id");
		TUser user = new TUser();
		user = (TUser)request.getSession().getAttribute("user");
		Degisn de = new Degisn();
		de.setStockId(Integer.parseInt(id));
		de.setUserId(user.getUserId());
		ide.save(de);
		return mapping.findForward("addstockby");
	}
	//列出用户所选股票及设置信息
	public ActionForward listset(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List l = new ArrayList();
		List degisn= new ArrayList();
		TUser user = new TUser();
		user = (TUser)request.getSession().getAttribute("user");
        l = ide.findByProperty("userId", user.getUserId());
        for(int i=0;i<l.size();i++)
        {
        	Degisn s = new Degisn();
        	s = (Degisn) l.get(i);
        	degisn.add(s);
        }
        request.setAttribute("degisn", degisn);
		return mapping.findForward("listset");
	}
	//设置股票信息
	public ActionForward setdesign(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String id = request.getParameter("id");
		Degisn des = new Degisn();
		des = ide.findById(Integer.parseInt(id));
        request.setAttribute("degisn", des);
		return mapping.findForward("setdesign");
	}
	//更新设置股票信息
	public ActionForward updatedesign(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TUser user = new TUser();
		user = (TUser)request.getSession().getAttribute("user");
		StockForm de = (StockForm) form;
		Degisn des = new Degisn();
		des.setDegisnId(de.getDegisnId());
		des.setMax(de.getMax());
		des.setMin(de.getMin());
		des.setDiff(de.getDiff());
		des.setUserId(user.getUserId());
		des.setStockId(de.getStock_id());
		ide.update(des);
		return mapping.findForward("tolistset");
	}
	//列出用户所选股票
	public ActionForward liststockbyuser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List l = new ArrayList();
		List stock= new ArrayList();
		TUser user = new TUser();
		user = (TUser)request.getSession().getAttribute("user");
        l = is.liststockbyuser(user.getUserId().toString());
        for(int i=0;i<l.size();i++)
        {
        	Stock s = new Stock();
        	Object[] obj = (Object[])l.get(i);
        	String ss = obj[0].toString();
        	s.setStockId(Integer.parseInt(obj[0].toString()));
        	s.setStockCode(obj[1].toString());
        	s.setStockName(obj[2].toString());
        	s.setStockInfo(obj[3].toString());
        	stock.add(s);
        }
     
        request.setAttribute("stock", stock);
		return mapping.findForward("liststockbyuser");
	}
	//列出用户所选股票
	public ActionForward getPic(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id=request.getParameter("id");
		String num=request.getParameter("num");
        request.setAttribute("id", id);
        request.setAttribute("num", num);
		return mapping.findForward("getPic");
	}
}