/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mms.struts.form;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.mms.pojo.AssetType;
import com.mms.pojo.Employee;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2009
 * 
 * XDoclet definition:
 * @struts.form name="assetForm"
 */
public class AssetForm extends ActionForm {
	
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer assetId;
	private AssetType assetType;
	private Employee employee;
	private String assetNumber;
	private String assetName;
	private String assetUseType;
	private String assetState;
	private Date assetUseToYear;
	private String assetUseTime;
	private Date assetBuyTime;
	private String assetFactory;
	private String assetModelType;
	private Double assetPrice;
	
	private Integer assetTypeId;
	private Integer assetEmployee;
	
	
	

	public Integer getAssetTypeId() {
		return assetTypeId;
	}

	public void setAssetTypeId(Integer assetTypeId) {
		this.assetTypeId = assetTypeId;
	}

	public Integer getAssetEmployee() {
		return assetEmployee;
	}

	public void setAssetEmployee(Integer assetEmployee) {
		this.assetEmployee = assetEmployee;
	}

	public AssetType getAssetType() {
		return assetType;
	}

	public Employee getEmployee() {
		return employee;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Integer getAssetId() {
		return assetId;
	}

	public void setAssetId(Integer assetId) {
		this.assetId = assetId;
	}

	
	public String getAssetNumber() {
		return assetNumber;
	}

	public void setAssetNumber(String assetNumber) {
		this.assetNumber = assetNumber;
	}

	public String getAssetName() {
		return assetName;
	}

	public void setAssetName(String assetName) {
		this.assetName = assetName;
	}

	public String getAssetUseType() {
		return assetUseType;
	}

	public void setAssetUseType(String assetUseType) {
		this.assetUseType = assetUseType;
	}

	

	public String getAssetUseTime() {
		return assetUseTime;
	}

	public void setAssetUseTime(String assetUseTime) {
		this.assetUseTime = assetUseTime;
	}


	public String getAssetFactory() {
		return assetFactory;
	}

	public void setAssetFactory(String assetFactory) {
		this.assetFactory = assetFactory;
	}

	public String getAssetModelType() {
		return assetModelType;
	}

	public void setAssetModelType(String assetModelType) {
		this.assetModelType = assetModelType;
	}

	public Double getAssetPrice() {
		return assetPrice;
	}

	public void setAssetPrice(Double assetPrice) {
		this.assetPrice = assetPrice;
	}
	
	public String getAssetState() {
		return assetState;
	}

	public void setAssetState(String assetState) {
		this.assetState = assetState;
	}

	public Date getAssetUseToYear() {
		return assetUseToYear;
	}

	public void setAssetUseToYear(Date assetUseToYear) {
		this.assetUseToYear = assetUseToYear;
	}

	public Date getAssetBuyTime() {
		return assetBuyTime;
	}

	public void setAssetBuyTime(Date assetBuyTime) {
		this.assetBuyTime = assetBuyTime;
	}

	public void setAssetType(AssetType assetType) {
		this.assetType = assetType;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	

	
}