/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mms.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.mms.pojo.Asset;
import com.mms.pojo.Employee;

/** 
 * MyEclipse Struts
 * Creation date: 10-17-2009
 * 
 * XDoclet definition:
 * @struts.form name="borrowForm"
 */
public class BorrowForm extends ActionForm {

	private Integer borrowId;
	private Asset asset;
	private Employee employeeByBorrowAdminCheck;
	private Employee employeeByUserId;
	private Date borrowTime;
	private Date borrowReturnTimeAp;
	private Date borrowReturnTime;
	private Date borrowBorrowedTime;
	
	
	
	public Integer getBorrowId() {
		return borrowId;
	}

	public void setBorrowId(Integer borrowId) {
		this.borrowId = borrowId;
	}

	public Asset getAsset() {
		return asset;
	}

	public void setAsset(Asset asset) {
		this.asset = asset;
	}

	public Employee getEmployeeByBorrowAdminCheck() {
		return employeeByBorrowAdminCheck;
	}

	public void setEmployeeByBorrowAdminCheck(Employee employeeByBorrowAdminCheck) {
		this.employeeByBorrowAdminCheck = employeeByBorrowAdminCheck;
	}

	public Employee getEmployeeByUserId() {
		return employeeByUserId;
	}

	public void setEmployeeByUserId(Employee employeeByUserId) {
		this.employeeByUserId = employeeByUserId;
	}

	public Date getBorrowTime() {
		return borrowTime;
	}

	public void setBorrowTime(Date borrowTime) {
		this.borrowTime = borrowTime;
	}

	public Date getBorrowReturnTimeAp() {
		return borrowReturnTimeAp;
	}

	public void setBorrowReturnTimeAp(Date borrowReturnTimeAp) {
		this.borrowReturnTimeAp = borrowReturnTimeAp;
	}

	public Date getBorrowReturnTime() {
		return borrowReturnTime;
	}

	public void setBorrowReturnTime(Date borrowReturnTime) {
		this.borrowReturnTime = borrowReturnTime;
	}

	public Date getBorrowBorrowedTime() {
		return borrowBorrowedTime;
	}

	public void setBorrowBorrowedTime(Date borrowBorrowedTime) {
		this.borrowBorrowedTime = borrowBorrowedTime;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}